Version = "1"
FontSize = 30
TargetFPS = 120
IndentSize = 2
FontRegular = "JetBrainsMonoNerdFont-Regular.ttf"
FontBold = "JetBrainsMonoNerdFont-Bold.ttf"
FontItalic = "JetBrainsMonoNerdFont-Italic.ttf"
PrimaryColor = "#0b0e14"
SecondaryColor = "#05080e"
TertiaryColor = "#21272d"
AccentColor = "#a37acc"
AccentColor2 = "#43b0e6"
DefaultFontColor = "#c9c7be"
HighlightFontColor = "#aad84c"
SecondaryFontColor = "#33363c"
KeywordsFontColor = "#ffb454"
FunctionsFontColor = "#f06e5b"
VariablesFontColor = "#c9c7be"
LiteralsFontColor = "#aad748"
RelativeLineNumbers = true
